"""Deterministic guardrails for the Autonumerics pipeline.

This package holds the checks that must **not** be regenerated by an LLM: spec
validation, the analytic-reference check, the requirements re-audit, the leakage
scans, and numeric-claim binding. See ``docs/plan-hallucination-guardrails.md``.

It also holds the **numerical verification kernel** (``verifylib.kernel``): the grid
ladders, Richardson and the GCI guards, the D1 operator residual, the invariant
registry, the MMS and degenerate-limit drivers, the SDE surrogates, CRN and Dynkin
-- and the scoring rubrics themselves. That is ``docs/plan-no-closed-form.md``'s
deliverable. Both halves share ``verifylib.operator`` for stencils and the
restricted expression namespace, so the reference check and the residual gate can
never disagree about what ``lap_u`` means (guardrails §14 C1).

The two halves answer different questions and that is why they are one package.
The guards ask "is this artifact well-formed and is its claimed answer checkable?";
the kernel asks "how accurate is this solver, and what does that rest on?". Both
must be deterministic, and neither may be regenerated by the agent it grades.

Every guard runs in two places: as a hook, for fast in-loop correction, and as a
gate that does not depend on an agent cooperating. That is not belt-and-braces --
a hook is feedback, not enforcement. Measured: when a hook contradicts an
instruction the agent stops, leaves the invalid file on disk, and escalates to the
user, and in a headless run nobody answers. ``gate.py`` is the composition both
call; ``cli.py`` is the single entry point.

Status: complete. Guardrails layers 1-5; layers 6 and 7 deferred except the canaries
under ``tests/canaries/``. The kernel covers the PDE and SDE paths, the D1 residual
and the scoring tables; ``cli.py evaluate <plan_dir>`` is its entry point.
"""

__version__ = "0.1.0"
