"""Deterministic guardrails for the Autonumerics pipeline.

This package holds the checks that must **not** be regenerated by an LLM: spec
validation, the analytic-reference check, the requirements re-audit, the leakage
scans, and numeric-claim binding. See ``docs/plan-hallucination-guardrails.md``.

It deliberately does **not** hold the numerical verification kernel (ladders,
Richardson, D1, invariants, the SDE surrogates). That is
``docs/plan-no-closed-form.md``'s deliverable and will land alongside this, sharing
``verifylib.operator`` for its stencils -- see §14 C1 of the guardrails plan.

Every guard runs in two places: as a hook, for fast in-loop correction, and as a
gate that does not depend on an agent cooperating. That is not belt-and-braces --
a hook is feedback, not enforcement. Measured: when a hook contradicts an
instruction the agent stops, leaves the invalid file on disk, and escalates to the
user, and in a headless run nobody answers. ``gate.py`` is the composition both
call; ``cli.py`` is the single entry point.

Status: complete. Layers 1-5 of the plan; layers 6 and 7 are deferred, except the
two canaries under ``tests/canaries/`` that test these layers.
"""

__version__ = "0.1.0"
